import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <nav className='flex fixed top-0 left-0 justify-between items-center w-full p-6'>
        <div>
          <Link href="/">
            <Button className='mr-4 p-4 rounded-2xl bg-white text-black font-bold'>Recipes</Button>
          </Link>
        </div>
        <div>
        <Link href="/login">
        <Button className='mr-4 p-4 rounded-2xl bg-white text-black'>New Recipe</Button>
        </Link>
        <Link href="/login">
        <Button className='mr-4 p-4 rounded-2xl bg-white text-black'>Log in</Button>
        </Link>
        <Button className='mr-4 p-4 rounded-2xl bg-white text-black'>Log out</Button>
        <Button className='mr-4 p-4 rounded-2xl'>Account</Button>
        </div>
      </nav>
        {children}</body>
    </html>
  )
}
